### ISSUE TITLE
Display app in full-screen mode on tablets

### ISSUE THREAD

**Issue by marshmn** [waltheri/go-pattern-search#11]
If you save a link to the site to your home screen on a tablet, then when you use that to launch it you will find that it opens in a normal browser window. It would be better if it launched using the full screen (e.g. without the browser address bar etc.) so that it makes better use of the available screen real-estate.

Some sites (such as http://online-go.com) seem to manage to achieve this. If you save a link to that site on your home screen, then launching it feels much more like you are launching a native application - it launches full-screen. I'm not entirely sure how they are achieving this, but I think it may be related to this META tag in their head section:

`<meta name="apple-mobile-web-app-capable" content="yes">`

**Comment by waltheri** [comment]
Thanks for the tip, I added that meta tag. Let me know if it is working.

**Comment by marshmn** [comment]
Hi Waltheri,

I just tried it out on my (Android) tablet and it works perfectly! It feels much better to be able to use the full screen like this on a tablet!

Many thanks,
Matt
